name: RcRPG
main: RcRPG.Main
version: 2.0.1
author: 若尘
authors: ["若尘", "Mcayear"]
api: 2.0.1
load: POSTWORLD
website: https://github.com/RuoChen688/RcRPG-PNX
depend: ["EconomyAPI"]
softdepend: ["RcNPC", "RsNPC", "PlayerPoint", "LittleMonster", "HealthAPI", "Tips"]
